name: build static react files
on:
  push:
    paths:
      - /Site-3/hello-react/
      
jobs:
  build_static_react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: cd Site-3/hello-react
      - run: npm ci
      #- run: npm test
      - run: npm run build
